package davids.unitfour;

import java.awt.*;
import java.io.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.sound.sampled.*;
import javax.swing.table.DefaultTableModel;

/* Name: David Shcherbatykh 
 * Wednesday, Nov. 22
 * ICS3U 
 * Description: A simple POS terminal for a refurbished computer system store named TechRevive. You must login 
 * with the account password TR123! and the username of your account (up to the user) that is 18 characters or less.
 * The store has laptops and PCs and you can add them to your cart which is shown on the left and at checkout.
 * The hardware details of the computer systems are displayed below their respective images. A bundle is available
 * for purchase in the PC section that includes a PC, keyboard, and mouse that is on sale. You can remove items from 
 * your cart by selecting the item you wish to remove and pressing the remove button. If you wish to clear the items from
 * your cart you can press the clear button. Finally when you are ready to purchase you may press the checkout button to 
 * finalize your order that displays the number of items in your cart, subtotal, tax, and total of your purchase. To make
 * another purchase you may press the Back to Store button.
 */
public class TRStore extends javax.swing.JFrame {

    /**
     * Creates new form TRStore
     */
    public static String usrname = ""; // Global username to be used as a parameter 

    public DecimalFormat df = new DecimalFormat("0.00");

    public int itemsInCart = 0; // Global variables for names and prices
    public double laptop1Price = 179.00;
    public String laptop1Name = "Lenovo L470";
    public double laptop2Price = 249.00;
    public String laptop2Name = "HP Elitebook 840 G2";
    public double laptop3Price = 379.00;
    public String laptop3Name = "DELL Latitude 7490";
    public double PC1Price = 218.94;
    public String PC1Name = "Dell Optiplex 5040";
    public double PC2Price = 229.00;
    public String PC2Name = "Apple Mac Mini A1347";
    public double PC3Price = 299.99;
    public String PC3Name = "HP ProDesk 600 G4";
    public double PC4Price = 369.54;
    public String PC4Name = "DELL 7040 BUNDLE";
    public double subtotal = 0;

    /**
     * Username from login is used to welcome user and if there was no username
     * inputted it will greet the user as "shopper". TRStore method centres its
     * JFrame and also runs audio file for music.
     *
     * @param usrname
     */
    public TRStore(String usrname) {
        initComponents();
        subtotalNum.setText("$0.00"); // Sets intital text for subtotal and items in cart
        itemsInCartNum.setText("0");

        this.usrname = usrname;
        if (usrname.equals("")) {
            welcomeLbl.setText("Hello Shopper!"); // Welcomes user 
        } else {
            welcomeLbl.setText("Hello " + this.usrname + "!"); // If no username is inputted then "shopper" replaces it
        }
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();

        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);

        try {
            File audioFile = new File("music.au");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            Clip audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            audioClip.loop(Clip.LOOP_CONTINUOUSLY); // Loops store music
        } catch (FileNotFoundException | UnsupportedAudioFileException | LineUnavailableException e) {
            System.out.println("The file does not exist or could not be found");
            System.err.println("FileNotFoundException: " + e.getMessage());
        } catch (IOException e) {
            System.out.println("Problem reading file");
            System.err.println("IOException: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutDialog = new javax.swing.JDialog();
        cart1 = new javax.swing.JScrollPane();
        finalCartTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        totalLbl = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        finalNumOfItems = new javax.swing.JLabel();
        finalSubtotal = new javax.swing.JLabel();
        taxLbl = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        loginExitBtn = new javax.swing.JButton();
        cart = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        laptop3Add = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        laptop2Add = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        laptop1Add = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        PC4Add = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        PC1Add = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        PC2Add = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        PC3Add = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        subtotalNum = new javax.swing.JLabel();
        itemsInCartNum = new javax.swing.JLabel();
        removeBtn = new javax.swing.JButton();
        itemsLbl = new javax.swing.JLabel();
        subtotalLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        clearBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        checkoutDialog.setTitle("Checkout");
        checkoutDialog.setMinimumSize(new java.awt.Dimension(1200, 600));
        checkoutDialog.setResizable(false);
        checkoutDialog.setSize(new java.awt.Dimension(1200, 600));
        checkoutDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finalCartTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finalCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        cart1.setViewportView(finalCartTable);

        checkoutDialog.getContentPane().add(cart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 480));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLbl.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        totalLbl.setText("$Total");
        jPanel5.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel33.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel33.setText("Total:");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel34.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel34.setText("Subtotal:");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel35.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel35.setText("Tax:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jPanel11.setBackground(new java.awt.Color(102, 255, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel2.setText("Order placed. Estimated shipping time is 3-5 business days.");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 690, 100));

        jLabel37.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel37.setText("# of Items Purchased: ");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        finalNumOfItems.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        finalNumOfItems.setText("Items");
        jPanel5.add(finalNumOfItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        finalSubtotal.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        finalSubtotal.setText("$Subtotal");
        jPanel5.add(finalSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        taxLbl.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        taxLbl.setText("$Tax");
        jPanel5.add(taxLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 730, 480));

        jLabel36.setFont(new java.awt.Font("HP Simplified", 1, 45)); // NOI18N
        jLabel36.setText("Thank you for shopping at TechRevive!");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        loginExitBtn.setBackground(new java.awt.Color(255, 153, 153));
        loginExitBtn.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        loginExitBtn.setText("Back to Store");
        loginExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitBtnActionPerformed(evt);
            }
        });
        jPanel4.add(loginExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 140, 50));

        checkoutDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TechRevive Store");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        cart.setViewportView(cartTable);

        getContentPane().add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 480));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laptop3Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        laptop3Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        laptop3Add.setText("  Add to Cart");
        laptop3Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        laptop3Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptop3AddActionPerformed(evt);
            }
        });
        jPanel8.add(laptop3Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/laptop3.jpg"))); // NOI18N
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Eras Bold ITC", 0, 22)); // NOI18N
        jLabel27.setText("DELL Latitude 7490");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Core i5 8350u 3.6GHz,");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("8GB, 256GB SSD, 14.1\", 1920");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("  x1080, HDMI, Wifi Webcam, ");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Win10 pro, Win11 option");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel32.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel32.setText("$379.00");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 280, 480));

        jPanel9.setBackground(new java.awt.Color(153, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laptop2Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        laptop2Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        laptop2Add.setText("  Add to Cart");
        laptop2Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        laptop2Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptop2AddActionPerformed(evt);
            }
        });
        jPanel9.add(laptop2Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/laptop2.jpg"))); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Eras Bold ITC", 0, 22)); // NOI18N
        jLabel20.setText("HP Elitebook 840 G2");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Core i5 5200u 2.9Ghz,");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("8GB, 256GB SSD, 14\" 1366x768, ");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText(" HDMI, Wifi, Bluetooth, Webcam,");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText(" Windows 10");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel25.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel25.setText("$249.00");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 280, 480));

        jPanel10.setBackground(new java.awt.Color(153, 255, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Core i3 7100u 2.4Ghz,");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        laptop1Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        laptop1Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        laptop1Add.setText("  Add to Cart");
        laptop1Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        laptop1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptop1AddActionPerformed(evt);
            }
        });
        jPanel10.add(laptop1Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/laptop1.jpg"))); // NOI18N
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Eras Bold ITC", 0, 22)); // NOI18N
        jLabel12.setText("Lenovo L470");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("8GB, 128GB SSD, 14\" 1366x768,");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText(" Win10 pro");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText(" Wifi, Bluetooth, Webcam,");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel15.setText("$179.00");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 480));

        jTabbedPane1.addTab("Laptops", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setText("Intel i7, 32GB, 1TB SSD,");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        PC4Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        PC4Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        PC4Add.setText("  Add to Cart");
        PC4Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PC4Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PC4AddActionPerformed(evt);
            }
        });
        jPanel12.add(PC4Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel43.setText("24\" Monitor + Keyboard");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel42.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        jLabel42.setText("Dell 7040 BUNDLE");
        jPanel12.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setText("and Mouse");
        jPanel12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel47.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        jLabel47.setText("_______");
        jLabel47.setToolTipText("SAVE $429 - Expires 27/11/2023");
        jPanel12.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel62.setText("Wifi, Win10 Pro Desktop +");
        jPanel12.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PC4.jpg"))); // NOI18N
        jPanel12.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel48.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel48.setText("$369.54");
        jLabel48.setToolTipText("SAVE $429 - Expires 27/11/2023");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel49.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        jLabel49.setText("$798.54");
        jLabel49.setToolTipText("SAVE $429 - Expires 27/11/2023");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 210, 480));

        jPanel15.setBackground(new java.awt.Color(153, 255, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel63.setText("High Performance Desktop");
        jPanel15.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        PC1Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        PC1Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        PC1Add.setText("  Add to Cart");
        PC1Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PC1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PC1AddActionPerformed(evt);
            }
        });
        jPanel15.add(PC1Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 30));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel65.setText("32GB RAM, New 1TB SSD,");
        jPanel15.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel66.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        jLabel66.setText("Dell Optiplex 5040");
        jPanel15.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel15.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel68.setText("Win10 Home");
        jPanel15.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel69.setText("Wifi, HDMI,");
        jPanel15.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel70.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel70.setText("$218.94");
        jPanel15.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel71.setText("Intel Quad Core i5 6500,");
        jPanel15.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PC1.jpg"))); // NOI18N
        jPanel15.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 480));

        jPanel16.setBackground(new java.awt.Color(153, 255, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel72.setText("Late 2014");
        jPanel16.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        PC2Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        PC2Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        PC2Add.setText("  Add to Cart");
        PC2Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PC2Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PC2AddActionPerformed(evt);
            }
        });
        jPanel16.add(PC2Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 30));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel74.setText("1TB HD, HDMI,");
        jPanel16.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel75.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        jLabel75.setText("A1347");
        jPanel16.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel16.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel78.setText("OSX 10.13 High Sierra");
        jPanel16.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel79.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel79.setText("$229.00");
        jPanel16.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel80.setText("Intel i5-4278U, 8GB Ram,");
        jPanel16.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PC2.jpg"))); // NOI18N
        jPanel16.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel93.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        jLabel93.setText("Apple Mac Mini");
        jPanel16.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 210, 480));

        jPanel17.setBackground(new java.awt.Color(153, 255, 153));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel81.setText("Small Form Factor");
        jPanel17.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        PC3Add.setFont(new java.awt.Font("Doppio One", 0, 14)); // NOI18N
        PC3Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartIcon.png"))); // NOI18N
        PC3Add.setText("  Add to Cart");
        PC3Add.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PC3Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PC3AddActionPerformed(evt);
            }
        });
        jPanel17.add(PC3Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 30));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel83.setText("512GB SSD, 16GB RAM,");
        jPanel17.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel84.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        jLabel84.setText("HP ProDesk 600 G4");
        jPanel17.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel17.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel86.setText("Win10 Pro");
        jPanel17.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel87.setText("LAN Connectivity,");
        jPanel17.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel88.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel88.setText("$299.99");
        jPanel17.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel89.setText("Intel Core i5-8500,");
        jPanel17.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PC3.png"))); // NOI18N
        jPanel17.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 210, 480));

        jTabbedPane1.addTab("PCs", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 950, 530));

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtotalNum.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        subtotalNum.setText("$Subtotal");
        jPanel6.add(subtotalNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        itemsInCartNum.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        itemsInCartNum.setText("NumInCart");
        jPanel6.add(itemsInCartNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 190, 30));

        removeBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        removeBtn.setText("Remove from Cart");
        removeBtn.setToolTipText("Select item in cart and press ");
        removeBtn.setEnabled(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel6.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 50));

        itemsLbl.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        itemsLbl.setText("Items in Cart: ");
        jPanel6.add(itemsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 30));

        subtotalLbl.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        subtotalLbl.setText("Subtotal:");
        jPanel6.add(subtotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 380, 140));

        jPanel7.setBackground(new java.awt.Color(51, 204, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setEnabled(false);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel7.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 90, 83));

        checkoutBtn.setBackground(new java.awt.Color(51, 255, 51));
        checkoutBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        checkoutBtn.setText("Checkout");
        checkoutBtn.setEnabled(false);
        checkoutBtn.setName(""); // NOI18N
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        jPanel7.add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 81));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 380, 110));

        jPanel1.setBackground(new java.awt.Color(35, 79, 86));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("the negative effect of manafacturing new devices.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 350, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Welcome to TechRevive, where technology meets compassion! At TechRevive, we specialize in ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 710, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("providing high-quality refurbished computer systems with a mission. Our aim extends beyond ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("delivering top-notch devices; it's about making a positive impact on the environment and to");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 650, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("communities in need. By refurbishing used, unwanted, or end-of-life computers, we are");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 630, 20));

        welcomeLbl.setFont(new java.awt.Font("HP Simplified", 1, 38)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 204, 153));
        welcomeLbl.setText("Hello *username*");
        welcomeLbl.setToolTipText("");
        jPanel1.add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 650, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("recycling and extending the life of electronics to help reduce electronic waste and minimizing");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 670, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 950, 220));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/storeBkg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Subtotal method calculates the current total of prices of the items in
     * cart before tax. It is called whenever the cart is updated which
     * recalculates the subtotal to account for the change.
     */
    public void subtotal() {

        subtotal = 0; // Reset subtotal to 0 to prepare for recalculation of subtotal

        for (int i = 0; i < cartTable.getRowCount(); i++) {
            subtotal += Double.parseDouble(cartTable.getValueAt(i, 2).toString()); // Gets value of each item from cart and adds together
        }

        subtotalNum.setText("$" + df.format(subtotal)); // Updates subtotal and formats it

        if (itemsInCart > 0) { // Enable buttons if there are items in cart
            clearBtn.setEnabled(true);
            checkoutBtn.setEnabled(true);
            removeBtn.setEnabled(true);
        }
    }

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        model.setRowCount(0); // Resets all values to 0
        subtotalNum.setText("$0.00");
        itemsInCartNum.setText("0");
        itemsInCart = 0;

        clearBtn.setEnabled(false); // Disables all buttons since there is no need to perform actions
        checkoutBtn.setEnabled(false);
        removeBtn.setEnabled(false);
    }//GEN-LAST:event_clearBtnActionPerformed

    /* The following events are for adding an item to cart. They first loop through the cartTable to find the item they are looking for
    * and then store that index in variable existingItemIndex which is the index of the row of the item to add to and starts at -1 
    * to make sure it isn't mixed up with indexes and to not execute the rest of the code if the item is not there. It then 
    * retrieves and stores the original quantities and prices of the item and then adds to them by 1 or their price, respectively. 
    * If it is the first time it is being added, in the cartTable a new row is created for that item with its details. Number of items in cart is 
    * updated and subtotal() is called to update the new subtotal that includes the item added.
     */

    private void laptop3AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptop3AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(laptop3Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + laptop3Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{laptop3Name, "1", df.format(laptop3Price)});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_laptop3AddActionPerformed

    private void laptop2AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptop2AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(laptop2Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + laptop2Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{laptop2Name, "1", df.format(laptop2Price)});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_laptop2AddActionPerformed

    private void laptop1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptop1AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(laptop1Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + laptop1Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{laptop1Name, "1", df.format(laptop1Price)});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_laptop1AddActionPerformed

    private void PC4AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PC4AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(PC4Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + PC4Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{PC4Name, "1", PC4Price});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_PC4AddActionPerformed

    private void PC1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PC1AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(PC1Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + PC1Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{PC1Name, "1", PC1Price});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_PC1AddActionPerformed

    private void PC2AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PC2AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(PC2Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + PC2Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{PC2Name, "1", df.format(PC2Price)});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_PC2AddActionPerformed

    private void PC3AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PC3AddActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int existingItemIndex = -1;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(PC3Name)) {
                existingItemIndex = i;
                break;
            }
        }

        if (existingItemIndex > -1) {
            int ogQuantity = Integer.parseInt(model.getValueAt(existingItemIndex, 1).toString());
            model.setValueAt(ogQuantity + 1, existingItemIndex, 1);

            double ogAmount = Double.parseDouble(model.getValueAt(existingItemIndex, 2).toString());
            model.setValueAt(df.format(ogAmount + PC3Price), existingItemIndex, 2);
        } else {
            model.addRow(new Object[]{PC3Name, "1", PC3Price});
        }

        itemsInCart++;
        itemsInCartNum.setText("" + itemsInCart);
        subtotal();
    }//GEN-LAST:event_PC3AddActionPerformed


    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int removeItem = cartTable.getSelectedRow(); // Intializes the index of the row that is selected to be the item being removed

        if (removeItem >= 0) { // In case of nothing to remove
            double removePrice = Double.parseDouble(model.getValueAt(removeItem, 2).toString()) / Double.parseDouble(model.getValueAt(removeItem, 1).toString()); // Takes the price amount (price total of the items of the same type) of the item to be deleted and divides by the quantity of the items to get the price of a single item

            if ((model.getValueAt(removeItem, 1)).toString().equals(Integer.toString(1))) { // Checks if there is only 1 item in row so it can remove the full row
                model.removeRow(removeItem);
            } else {
                int ogQuantity = Integer.parseInt(model.getValueAt(removeItem, 1).toString()); // Finds original quantity of item and stores it
                model.setValueAt(ogQuantity - 1, removeItem, 1); // Subtracts 1 from the original quantity (removes 1 item)

                double ogAmount = Double.parseDouble(model.getValueAt(removeItem, 2).toString()); // Finds original amount price of item and stores it
                model.setValueAt(df.format(ogAmount - removePrice), removeItem, 2); // Subtracts the price of one item from the original amount
            }
            subtotal(); // Recalculates new subtotal by calling method
            itemsInCart -= 1; // Subtracts 1 from items in cart
            itemsInCartNum.setText("" + itemsInCart); // Updates label
        }
        if (model.getRowCount() == 0) { // If last item was removed from cart then disable all cart buttons since there are no actions to be made
            clearBtn.setEnabled(false);
            checkoutBtn.setEnabled(false);
            removeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        DefaultTableModel finalModel = (DefaultTableModel) finalCartTable.getModel();

        checkoutDialog.setLocationRelativeTo(this); // Centres dialog and makes visible
        checkoutDialog.setVisible(true);

        finalSubtotal.setText("$" + df.format(subtotal)); // Displays final subtotal and items in cart
        finalNumOfItems.setText("" + itemsInCart);

        double tax = subtotal * 0.13; // Calculates the tax (13%) of the subtotal and displays it
        taxLbl.setText("$" + df.format(tax));
        totalLbl.setText("$" + df.format(subtotal + tax));

        int rowCount = cartTable.getRowCount();

        for (int i = 0; i < rowCount; i++) { // Loops through the cartTable, stores data into ArrayList, and copies data from ArrayList to finalCartTable (receipt) 
            ArrayList<Object> rowData = new ArrayList<>();
            for (int j = 0; j < model.getColumnCount(); j++) {
                rowData.add(model.getValueAt(i, j));
            }
            finalModel.addRow(rowData.toArray());
        }


    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void loginExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        DefaultTableModel finalModel = (DefaultTableModel) finalCartTable.getModel();

        checkoutDialog.dispose(); // Closes checkout
        model.setRowCount(0); // Sets all values back to 0 for next purchase
        finalModel.setRowCount(0);
        subtotalNum.setText("$0.00");
        itemsInCartNum.setText("0");
        itemsInCart = 0;
        finalSubtotal.setText("$0.00");
        finalNumOfItems.setText("0");
        taxLbl.setText("$0.00");
        totalLbl.setText("$0.00");

        clearBtn.setEnabled(false); // Disables all buttons again 
        checkoutBtn.setEnabled(false);
        removeBtn.setEnabled(false);

    }//GEN-LAST:event_loginExitBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRStore(usrname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PC1Add;
    private javax.swing.JButton PC2Add;
    private javax.swing.JButton PC3Add;
    private javax.swing.JButton PC4Add;
    private javax.swing.JScrollPane cart;
    private javax.swing.JScrollPane cart1;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JDialog checkoutDialog;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTable finalCartTable;
    private javax.swing.JLabel finalNumOfItems;
    private javax.swing.JLabel finalSubtotal;
    private javax.swing.JLabel itemsInCartNum;
    private javax.swing.JLabel itemsLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton laptop1Add;
    private javax.swing.JButton laptop2Add;
    private javax.swing.JButton laptop3Add;
    private javax.swing.JButton loginExitBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel subtotalLbl;
    private javax.swing.JLabel subtotalNum;
    private javax.swing.JLabel taxLbl;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
